language: ruby
cache: bundler

services:
  redis-server

rvm:
  - 2.2.0

script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - asviresh@gmail.com
    on_failure: change
    on_success: never
